server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: "jdbc:mariadb://localhost:3306/security?autoReconnect=true&&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false"
        username: cos
        password: cos1234
    
    mvc:
        view:
            prefix: /templates/
            suffix: .mustache

    jpa:
        defer-datasource-initialization: true
        open-in-view: false
        generate-ddl: true
        hibernate:
    
    security:
        user:
            name: kim
            password: kim
            roles: ADMIN